// <auto-generated />
namespace LiquorInventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletedduplicaterecordsindatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedduplicaterecordsindatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201708171657414_deleted duplicate records in database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
