// <auto-generated />
namespace LiquorInventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedaviewmodeltocomputetotalinventoryandpourcostaddingmigrationtotrytotroubleshootVMcontroller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedaviewmodeltocomputetotalinventoryandpourcostaddingmigrationtotrytotroubleshootVMcontroller));
        
        string IMigrationMetadata.Id
        {
            get { return "201708171845273_added a view model to compute total inventory and pour cost, adding migration to try to troubleshoot VM controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
