// <auto-generated />
namespace LiquorInventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class droppedcocktailcostandgotpourcostworkingandformatted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(droppedcocktailcostandgotpourcostworkingandformatted));
        
        string IMigrationMetadata.Id
        {
            get { return "201708172205176_dropped cocktail cost and got pour cost working and formatted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
