// <auto-generated />
namespace LiquorInventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdcontrollersandviewsforIngredientscocktailsandmonthlypourcost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdcontrollersandviewsforIngredientscocktailsandmonthlypourcost));
        
        string IMigrationMetadata.Id
        {
            get { return "201708171631082_created controllers and views for Ingredients, cocktails, and monthly pour cost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
